2024-03-01 22:04:36.944717: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "/home/sanghyuk.kim001/MELANOMA/melanoma-detection-CNN/train.py", line 178, in <module>
    = utilInstance.combineDatasets(aug_pkl)
  File "/home/sanghyuk.kim001/MELANOMA/melanoma-detection-CNN/melanoma/util.py", line 2408, in combineDatasets
    trainimgs_list = np.vstack(trainimgs_list)
  File "<__array_function__ internals>", line 5, in vstack
  File "/home/sanghyuk.kim001/anaconda3/envs/clean_chimera_env/lib/python3.9/site-packages/numpy/core/shape_base.py", line 283, in vstack
    return _nx.concatenate(arrs, 0)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: need at least one array to concatenate
